name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  # Atualizado para a versão mais recente

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Atualizado para a versão mais recente

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  # Atualizado para a versão mais recente
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          jeffersondevelopers/python-flask-email-verifier:latest
          jeffersondevelopers/python-flask-email-verifier:${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
